// Тестовые данные карточек (по макету внутри src)
export const cardsData = [
  {
    id: 1,
    topic: "Web Design",
    title: "Сверстать лендинг",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Изучить API",
    date: "31.10.23",
    status: "Нужно сделать",
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Подготовить тексты",
    date: "01.11.23",
    status: "В работе",
  },
  {
    id: 4,
    topic: "Testing",
    title: "Написать тест-кейсы",
    date: "02.11.23",
    status: "Тестирование",
  },
  {
    id: 5,
    topic: "Deploy",
    title: "Выкатить релиз",
    date: "03.11.23",
    status: "Готово",
  },
  {
    id: 6,
    topic: "Research",
    title: "Сравнить библиотеки",
    date: "01.11.23",
    status: "Без статуса",
  },
  {
    id: 7,
    topic: "Web Design",
    title: "Дизайн карточек",
    date: "02.11.23",
    status: "Нужно сделать",
  },
  {
    id: 8,
    topic: "Testing",
    title: "Интеграционные тесты",
    date: "04.11.23",
    status: "В работе",
  },
  {
    id: 9,
    topic: "Copywriting",
    title: "Правки контента",
    date: "05.11.23",
    status: "Тестирование",
  },
  {
    id: 10,
    topic: "Deploy",
    title: "Настроить CI",
    date: "06.11.23",
    status: "Готово",
  },
];
